### ISSUE TITLE
Why the Class column?

### ISSUE THREAD

**Issue by joell67** [outeredge/edge-magento-module-customoptionimage#4]
Installed, looks good in backend. However, what is the Class columns you added and what do you need it for?

Also, how do I add 2 more columns for custom options:
-Qty, so each option has its own qty/is_in_stock when placing an order
-Status, set status 0/1 if option should be used or not

Rgds.

**Comment by davidwindell** [comment]
@joell67 we use the class to specify a custom CSS class to be applied to each option, for example `product-custom-option-{class}`
